local T = require "coq.lib.test"
local txt = require "coq.lib.text"

local drain = function(iter)
  local out = {}
  for v in iter do
    table.insert(out, v)
  end
  return out
end

T.describe({ "text.splitlines" }, function(test)
  test({ "yields a single line for a separator-free string" }, function()
    T.eq(drain(txt.splitlines "labrador"), { "labrador" })
  end)

  test({ "splits on LF" }, function()
    T.eq(drain(txt.splitlines "lil\nspot\nfido"), { "lil", "spot", "fido" })
  end)

  test({ "splits on CRLF as one separator" }, function()
    T.eq(drain(txt.splitlines "lil\r\nspot\r\nfido"), { "lil", "spot", "fido" })
  end)

  test({ "splits on bare CR" }, function()
    T.eq(drain(txt.splitlines "lil\rspot\rfido"), { "lil", "spot", "fido" })
  end)

  test({ "mixes line endings in one input" }, function()
    T.eq(drain(txt.splitlines "a\nb\r\nc\rd"), { "a", "b", "c", "d" })
  end)

  test({ "a trailing separator yields a final empty line" }, function()
    T.eq(drain(txt.splitlines "lil\n"), { "lil", "" })
    T.eq(drain(txt.splitlines "lil\r\n"), { "lil", "" })
    T.eq(drain(txt.splitlines "lil\r"), { "lil", "" })
  end)

  test({ "empty input yields one empty line" }, function()
    T.eq(drain(txt.splitlines ""), { "" })
  end)

  test({ "consecutive separators yield empty lines between them" }, function()
    T.eq(drain(txt.splitlines "a\n\nb"), { "a", "", "b" })
    T.eq(drain(txt.splitlines "a\r\n\r\nb"), { "a", "", "b" })
  end)

  test({ "iter is idempotent on nil — calls past end stay nil" }, function()
    local iter = txt.splitlines "lil"
    T.eq(iter(), "lil")
    T.eq(iter(), nil)
    T.eq(iter(), nil)
  end)
end)

T.describe({ "text.is_multiline" }, function(test)
  test({ "flat strings are not multiline" }, function()
    T.eq(txt.is_multiline "labrador", false)
    T.eq(txt.is_multiline "", false)
  end)

  test({ "LF, CR, or CRLF all count" }, function()
    T.eq(txt.is_multiline "lil\nspot", true)
    T.eq(txt.is_multiline "lil\rspot", true)
    T.eq(txt.is_multiline "lil\r\nspot", true)
  end)

  test({ "a trailing separator alone counts" }, function()
    T.eq(txt.is_multiline "lil\n", true)
  end)
end)

T.describe({ "text.lstrip" }, function(test)
  test({ "strips leading whitespace only" }, function()
    T.eq(txt.lstrip "   labrador", "labrador")
    T.eq(txt.lstrip "\t\nlabrador  ", "labrador  ")
  end)
  test({ "no leading whitespace is a no-op" }, function()
    T.eq(txt.lstrip "labrador", "labrador")
  end)
  test({ "all-whitespace becomes empty" }, function()
    T.eq(txt.lstrip "   ", "")
  end)
end)

T.describe({ "text.rstrip" }, function(test)
  test({ "strips trailing whitespace only" }, function()
    T.eq(txt.rstrip "labrador   ", "labrador")
    T.eq(txt.rstrip "  labrador\t\n", "  labrador")
  end)
  test({ "no trailing whitespace is a no-op" }, function()
    T.eq(txt.rstrip "labrador", "labrador")
  end)
  test({ "all-whitespace becomes empty" }, function()
    T.eq(txt.rstrip "   ", "")
  end)
end)

T.describe({ "text.has_any_prefix" }, function(test)
  test({ "matches when any prefix matches" }, function()
    T.eq(txt.startswith({ "lil", "spot" }, "spotlight"), true)
  end)
  test({ "no match when none of the prefixes apply" }, function()
    T.eq(txt.startswith({ "lil", "spot" }, "fido"), false)
  end)
  test({ "empty prefix list is false" }, function()
    T.eq(txt.startswith({}, "labrador"), false)
  end)
  test({ "empty line matches only against an empty prefix" }, function()
    T.eq(txt.startswith({ "lil" }, ""), false)
    T.eq(txt.startswith({ "" }, ""), true)
  end)
end)

T.describe({ "text.dedent" }, function(test)
  ---@param lines string[]
  ---@return string[]
  local collect = function(lines)
    return vim.iter(txt.dedent(lines)):totable()
  end
  test({ "strips the common leading whitespace from every line" }, function()
    T.eq(collect { "    lil", "    spot", "    fido" }, { "lil", "spot", "fido" })
  end)
  test({ "with no common indent, body is unchanged" }, function()
    T.eq(collect { "lil", "  spot", "fido" }, { "lil", "  spot", "fido" })
  end)
  test({ "ignores whitespace-only lines when computing the common prefix" }, function()
    T.eq(collect { "    lil", "", "    spot" }, { "lil", "", "spot" })
  end)
  test({ "partial common prefix keeps the remainder" }, function()
    T.eq(collect { "  lil", "    spot" }, { "lil", "  spot" })
  end)
  test({ "a single line is dedented" }, function()
    T.eq(collect { "\tlabrador" }, { "labrador" })
  end)
  test({ "tabs and spaces are treated literally (must match exactly)" }, function()
    T.eq(collect { "\tlil", "  spot" }, { "\tlil", "  spot" })
  end)
  test({ "empty input yields empty" }, function()
    T.eq(collect {}, {})
  end)
end)

T.describe({ "text.prefix_overlap" }, function(test)
  test({ "full overlap when needle is a suffix of haystack" }, function()
    T.eq(txt.prefix_overlap("@@for", "@for"), 4)
  end)
  test({ "partial overlap at the boundary" }, function()
    T.eq(txt.prefix_overlap("fo", "for"), 2)
  end)
  test({ "no overlap" }, function()
    T.eq(txt.prefix_overlap("xy", "for"), 0)
  end)
  test({ "either side empty yields zero" }, function()
    T.eq(txt.prefix_overlap("", "for"), 0)
    T.eq(txt.prefix_overlap("fido", ""), 0)
  end)
  test({ "needle longer than haystack capped by haystack length" }, function()
    T.eq(txt.prefix_overlap("@", "@for"), 1)
  end)
end)

T.describe({ "text.longest_common_prefix" }, function(test)
  test({ "equal strings → full length" }, function()
    T.eq(txt.longest_common_prefix("fido", "fido"), 4)
  end)
  test({ "a is prefix of b" }, function()
    T.eq(txt.longest_common_prefix("fi", "fido"), 2)
  end)
  test({ "b is prefix of a" }, function()
    T.eq(txt.longest_common_prefix("fido", "fi"), 2)
  end)
  test({ "diverge mid-string" }, function()
    T.eq(txt.longest_common_prefix("fn", "function"), 1)
  end)
  test({ "no shared prefix" }, function()
    T.eq(txt.longest_common_prefix("xy", "fido"), 0)
  end)
  test({ "either side empty yields zero" }, function()
    T.eq(txt.longest_common_prefix("", "fido"), 0)
    T.eq(txt.longest_common_prefix("fido", ""), 0)
  end)
end)

T.describe({ "text.subseq_end" }, function(test)
  test({ "strict prefix → end of prefix" }, function()
    T.eq(txt.subseq_end("wh", "while"), 2)
  end)
  test({ "subseq with skipped middle" }, function()
    T.eq(txt.subseq_end("fn", "function"), 3)
  end)
  test({ "subseq across longer gap" }, function()
    T.eq(txt.subseq_end("nvm", "nvim_api_*"), 4)
  end)
  test({ "exact match → end of str" }, function()
    T.eq(txt.subseq_end("fido", "fido"), 4)
  end)
  test({ "no chars match → 0" }, function()
    T.eq(txt.subseq_end("xyz", "abc"), 0)
  end)
  test({ "partial match before unmatched tail" }, function()
    -- 'f' at 1, 'n' at 3, 'x' not found → returns 3
    T.eq(txt.subseq_end("fnx", "function"), 3)
  end)
  test({ "empty subseq → 0" }, function()
    T.eq(txt.subseq_end("", "fido"), 0)
  end)
  test({ "empty str → 0" }, function()
    T.eq(txt.subseq_end("fido", ""), 0)
  end)
end)

T.describe({ "text.suffix_overlap" }, function(test)
  test({ "full overlap when needle is a prefix of haystack" }, function()
    T.eq(txt.suffix_overlap("@param@param", "@param"), 6)
  end)
  test({ "partial overlap at the boundary" }, function()
    T.eq(txt.suffix_overlap("do", "fido"), 2)
  end)
  test({ "no overlap" }, function()
    T.eq(txt.suffix_overlap("xy", "for"), 0)
  end)
  test({ "either side empty yields zero" }, function()
    T.eq(txt.suffix_overlap("", "for"), 0)
    T.eq(txt.suffix_overlap("fido", ""), 0)
  end)
end)
