local T = require "coq.lib.test"
local txt = require "coq.lib.text"

local drain = function(iter)
  local out = {}
  for v in iter do
    table.insert(out, v)
  end
  return out
end

T.describe("text.splitlines", function(test)
  test("yields a single line for a separator-free string", function()
    T.eq(drain(txt.splitlines "labrador"), { "labrador" })
  end)

  test("splits on LF", function()
    T.eq(drain(txt.splitlines "lil\nspot\nfido"), { "lil", "spot", "fido" })
  end)

  test("splits on CRLF as one separator", function()
    T.eq(drain(txt.splitlines "lil\r\nspot\r\nfido"), { "lil", "spot", "fido" })
  end)

  test("splits on bare CR", function()
    T.eq(drain(txt.splitlines "lil\rspot\rfido"), { "lil", "spot", "fido" })
  end)

  test("mixes line endings in one input", function()
    T.eq(drain(txt.splitlines "a\nb\r\nc\rd"), { "a", "b", "c", "d" })
  end)

  test("a trailing separator yields a final empty line", function()
    T.eq(drain(txt.splitlines "lil\n"), { "lil", "" })
    T.eq(drain(txt.splitlines "lil\r\n"), { "lil", "" })
    T.eq(drain(txt.splitlines "lil\r"), { "lil", "" })
  end)

  test("empty input yields one empty line", function()
    T.eq(drain(txt.splitlines ""), { "" })
  end)

  test("consecutive separators yield empty lines between them", function()
    T.eq(drain(txt.splitlines "a\n\nb"), { "a", "", "b" })
    T.eq(drain(txt.splitlines "a\r\n\r\nb"), { "a", "", "b" })
  end)

  test("iter is idempotent on nil — calls past end stay nil", function()
    local iter = txt.splitlines "lil"
    T.eq(iter(), "lil")
    T.eq(iter(), nil)
    T.eq(iter(), nil)
  end)
end)

T.describe("text.is_multiline", function(test)
  test("flat strings are not multiline", function()
    T.eq(txt.is_multiline "labrador", false)
    T.eq(txt.is_multiline "", false)
  end)

  test("LF, CR, or CRLF all count", function()
    T.eq(txt.is_multiline "lil\nspot", true)
    T.eq(txt.is_multiline "lil\rspot", true)
    T.eq(txt.is_multiline "lil\r\nspot", true)
  end)

  test("a trailing separator alone counts", function()
    T.eq(txt.is_multiline "lil\n", true)
  end)
end)

T.describe("text.lstrip", function(test)
  test("strips leading whitespace only", function()
    T.eq(txt.lstrip "   labrador", "labrador")
    T.eq(txt.lstrip "\t\nlabrador  ", "labrador  ")
  end)
  test("no leading whitespace is a no-op", function()
    T.eq(txt.lstrip "labrador", "labrador")
  end)
  test("all-whitespace becomes empty", function()
    T.eq(txt.lstrip "   ", "")
  end)
end)

T.describe("text.rstrip", function(test)
  test("strips trailing whitespace only", function()
    T.eq(txt.rstrip "labrador   ", "labrador")
    T.eq(txt.rstrip "  labrador\t\n", "  labrador")
  end)
  test("no trailing whitespace is a no-op", function()
    T.eq(txt.rstrip "labrador", "labrador")
  end)
  test("all-whitespace becomes empty", function()
    T.eq(txt.rstrip "   ", "")
  end)
end)

T.describe("text.has_any_prefix", function(test)
  test("matches when any prefix matches", function()
    T.eq(txt.startswith({ "lil", "spot" }, "spotlight"), true)
  end)
  test("no match when none of the prefixes apply", function()
    T.eq(txt.startswith({ "lil", "spot" }, "fido"), false)
  end)
  test("empty prefix list is false", function()
    T.eq(txt.startswith({}, "labrador"), false)
  end)
  test("empty line matches only against an empty prefix", function()
    T.eq(txt.startswith({ "lil" }, ""), false)
    T.eq(txt.startswith({ "" }, ""), true)
  end)
end)

T.describe("text.dedent", function(test)
  test("strips the common leading whitespace from every line", function()
    T.eq(txt.dedent { "    lil", "    spot", "    fido" }, { "lil", "spot", "fido" })
  end)
  test("with no common indent, body is unchanged", function()
    T.eq(txt.dedent { "lil", "  spot", "fido" }, { "lil", "  spot", "fido" })
  end)
  test("ignores whitespace-only lines when computing the common prefix", function()
    T.eq(txt.dedent { "    lil", "", "    spot" }, { "lil", "", "spot" })
  end)
  test("partial common prefix keeps the remainder", function()
    T.eq(txt.dedent { "  lil", "    spot" }, { "lil", "  spot" })
  end)
  test("a single line is dedented", function()
    T.eq(txt.dedent { "\tlabrador" }, { "labrador" })
  end)
  test("tabs and spaces are treated literally (must match exactly)", function()
    T.eq(txt.dedent { "\tlil", "  spot" }, { "\tlil", "  spot" })
  end)
  test("empty input yields empty", function()
    T.eq(txt.dedent {}, {})
  end)
end)
