---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_ver }}

      - run: |-
          curl --disable --fail --location --no-progress-meter -- 'https://ms-jpq.github.io/deb/pubkey.asc' | sudo -- gpg --batch --dearmor --yes --output /etc/apt/trusted.gpg.d/ms-jpq.gpg
          sudo -- apt update
          sudo -- apt install --yes -- neovim universal-ctags

      - run: |-
          pip3 install -- codespell
          codespell --skip ./artifacts/helo.yml --skip ./tests/shared/fuzzy.py --ignore-words-list assertIn thirdparty

      - run: |-
          make lint

      - run: |-
          python3 -m coq deps

      - run: |-
          make test
