---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: |-
          curl --disable --fail --location --no-progress-meter -- 'https://raw.githubusercontent.com/ms-jpq/deb/refs/heads/deb/pubkey.asc' | sudo -- gpg --batch --dearmor --yes --output /etc/apt/trusted.gpg.d/ms-jpq.gpg
          sudo -- tee -- /etc/apt/sources.list.d/ms-jpq.list <<-'EOF'
          deb https://raw.githubusercontent.com/ms-jpq/deb/refs/heads/deb/ /
          EOF

      - run: |-
          sudo -- apt update
          sudo -- apt install --yes -- neovim universal-ctags

      - run: |-
          pip3 install -- codespell
          codespell --skip ./artifacts/helo.yml --skip ./tests/shared/fuzzy.py --ignore-words-list assertIn thirdparty

      - run: |-
          make lint

      - run: |-
          python3 -m coq deps

      - run: |-
          make test

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: |-
          brew install -- make neovim universal-ctags

      - run: |-
          python3 -m coq deps

      - run: |-
          gmake lint

      - run: |-
          gmake test
